# -*- coding: utf-8 -*-
"""Python_Taining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bifw3VS57LWp2tjX9vxyRBVIbRgLZL66
"""

print("Hello World!!")

input("Perss Enter to exit")

Name=input("enter your name:-")
print("My Name is",Name)

#My first Python Program
a=2
b=5.4
c=a+b
print(c)
print(type(a))
print(type(b))

import keyword
print(keyword.kwlist)

x="123"
y=5
x+y

x="123"
y=5
int(x)+y

# Maya's Juice Shop

# Taking input from the user (customer)
customer_name = input("Enter your name: ")
apple_juice_sold = int(input("How many apple juices would you like to buy? = "))
orange_juice_sold = int(input("How many orange juices would you like to buy? = "))

# Fixed prices
apple_juice_price = 30       # integer
orange_juice_price = 40      # integer

# Boolean variable for weekend offer
is_weekend_input = input("Is it weekend? (yes/no): ")
is_weekend = is_weekend_input.lower() == 'yes'

# Calculate totals using operators
total_apple = apple_juice_price * apple_juice_sold
total_orange = orange_juice_price * orange_juice_sold
total_bill = total_apple + total_orange

# Print the bill summary
print("\n🧾 Juice Bill for", customer_name)
print("Apple Juice:", apple_juice_sold, "x ₹30 =", total_apple)
print("Orange Juice:", orange_juice_sold, "x ₹40 =", total_orange)
print("Total Bill: ₹", total_bill)

# Apply discount if it's the weekend
if is_weekend:
    discount = 0.1 * total_bill
    final_amount = total_bill - discount
    print("🎉 Weekend Discount: ₹", discount)
    print("Amount to Pay: ₹", final_amount)
else:
    print("Amount to Pay: ₹", total_bill)

# Maya's Juice Shop - Without using if-else

# Take user input
customer_name = input("Enter your name: ")
apple_juice_sold = int(input("How many apple juices would you like to buy? "))
orange_juice_sold = int(input("How many orange juices would you like to buy? "))

# Fixed prices
apple_juice_price = 30
orange_juice_price = 40

# Assume it's a weekend (set to True/False)
is_weekend_input = input("Is it weekend? (yes/no): ")
is_weekend = is_weekend_input.lower() == 'yes'

# Calculate total
total_apple = apple_juice_price * apple_juice_sold
total_orange = orange_juice_price * orange_juice_sold
total_bill = total_apple + total_orange

# Apply discount (10% if weekend, 0% if not)
discount_rate = 0.1 * is_weekend  # is_weekend is True (1) or False (0)
discount = total_bill * discount_rate
final_amount = total_bill - discount

# Print bill
print("\n🧾 Juice Bill for", customer_name)
print("Apple Juice:", apple_juice_sold, "x ₹30 =", total_apple)
print("Orange Juice:", orange_juice_sold, "x ₹40 =", total_orange)
print("Total Bill: ₹", total_bill)
print("Discount Applied: ₹", discount)
print("Amount to Pay: ₹", final_amount)